"""Constants gathered in one place"""

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

BLUE_SKY = (71, 93, 240)  # background color

BASTION_LEVEL = 200
LEFT_TOWER = 200  # right edge of left tower
RIGHT_TOWER = 600  # left edge of right tower
GROUND_LEVEL = 500  # incoming enemies and where the barrel breaks

PLAYER_START_POS =(SCREEN_WIDTH // 2, BASTION_LEVEL)
PLAYER_STEP = 5

BARREL_SPEED = 6

ENEMY_WALKING_SPEED = 4
ENEMY_CLIMBING_SPEED = -3
LADDERS = 7
LADDER_WIDTH = 50
FIRST_LADDER_POS = LEFT_TOWER + (RIGHT_TOWER - LEFT_TOWER - LADDERS * LADDER_WIDTH) // 2